// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function ChangePassword(arg1:model.ChangePasswordParam):Promise<Error>;

export function Greet(arg1:string):Promise<string>;

export function Keygen(arg1:string,arg2:string):Promise<string>;

export function LoadText(arg1:string):Promise<string>;

export function PostHttp(arg1:string,arg2:string):Promise<string>;

export function ReadMessage():Promise<main.Message>;

export function SaveText(arg1:string,arg2:string):Promise<Error>;

export function SetupN2N():Promise<Error>;

export function ShutdownN2N():Promise<Error>;

export function WaitForN2NFinish():Promise<void>;
