// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1) {
  return window['go']['main']['App']['ChangePassword'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Keygen(arg1, arg2) {
  return window['go']['main']['App']['Keygen'](arg1, arg2);
}

export function LoadText(arg1) {
  return window['go']['main']['App']['LoadText'](arg1);
}

export function PostHttp(arg1, arg2) {
  return window['go']['main']['App']['PostHttp'](arg1, arg2);
}

export function ReadMessage() {
  return window['go']['main']['App']['ReadMessage']();
}

export function SaveText(arg1, arg2) {
  return window['go']['main']['App']['SaveText'](arg1, arg2);
}

export function SetupN2N() {
  return window['go']['main']['App']['SetupN2N']();
}

export function ShutdownN2N() {
  return window['go']['main']['App']['ShutdownN2N']();
}

export function WaitForN2NFinish() {
  return window['go']['main']['App']['WaitForN2NFinish']();
}
